config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :shifts
  end
  resources :locations do
    resource :shift_locations
  end
root 'welcome#index'
end

app/models/shift_location.rb
class ShiftLocation < ApplicationRecord
  belongs_to :location
  has_many :shifts
end

app/controllers/shift_locations_controller.rb
class ShiftLocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shift_location, only: [:show, :edit, :update, :destroy]

  # GET /shift_locations
  # GET /shift_locations.json
  def index
    @shift_locations = ShiftLocation.all
  end

  # GET /shift_locations/1
  # GET /shift_locations/1.json
  def show
  end

  # GET /shift_locations/new
  def new
    @shift_location = ShiftLocation.new
  end

  # GET /shift_locations/1/edit
  def edit
  end

  # POST /shift_locations
  # POST /shift_locations.json
  def create
    @shift_location = ShiftLocation.new(shift_location_params)

    respond_to do |format|
      if @shift_location.save
        format.html { redirect_to @shift_location, notice: 'Shift location was successfully created.' }
        format.json { render :show, status: :created, location: @shift_location }
      else
        format.html { render :new }
        format.json { render json: @shift_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shift_locations/1
  # PATCH/PUT /shift_locations/1.json
  def update
    respond_to do |format|
      if @shift_location.update(shift_location_params)
        format.html { redirect_to @shift_location, notice: 'Shift location was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift_location }
      else
        format.html { render :edit }
        format.json { render json: @shift_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shift_locations/1
  # DELETE /shift_locations/1.json
  def destroy
    @shift_location.destroy
    respond_to do |format|
      format.html { redirect_to shift_locations_url, notice: 'Shift location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift_location
      @shift_location = ShiftLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_location_params
      params.fetch(:shift_location, {})
    end
end

app/helpers/shift_locations_helper.rb
module ShiftLocationsHelper
end

app/views/shift_locations/_form.html.erb
<%= form_with(model: shift_location, local: true) do |form| %>
  <% if shift_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift_location.errors.count, "error") %> prohibited this shift_location from being saved:</h2>

      <ul>
      <% shift_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shift_locations/edit.html.erb
<h1>Editing Shift Location</h1>

<%= render 'form', shift_location: @shift_location %>

<%= link_to 'Show', @shift_location %> |
<%= link_to 'Back', shift_locations_path %>

app/views/shift_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shift Locations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shift_locations.each do |shift_location| %>
      <tr>
        <td><%= link_to 'Show', shift_location %></td>
        <td><%= link_to 'Edit', edit_shift_location_path(shift_location) %></td>
        <td><%= link_to 'Destroy', shift_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift Location', new_shift_location_path %>

app/views/shift_locations/new.html.erb
<h1>New Shift Location</h1>

<%= render 'form', shift_location: @shift_location %>

<%= link_to 'Back', shift_locations_path %>

app/views/shift_locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_shift_location_path(@shift_location) %> |
<%= link_to 'Back', shift_locations_path %>