config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :shifts
  end
  resources :locations do
    resource :shift_locations
  end
root 'welcome#index'
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :date, presence: true
  has_many :locations
  has_many :shift_locations
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params.permit(:name, :date, :description, :location))

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params.permit(:name, :date, :description, :location))
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {})
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= bootstrap_form_for(@event) do |f| %>
    <%= f.text_field :name %>
    <%= f.date_select :date %>
    <%= f.text_area :description %>
    <%= f.select :location, Location.all.collect {|l| [l.name, l.id] } %>
    <%= f.submit %>
  <% end %>


<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Datum</th>
      <th>Beschreibung</th>
      <th>Ort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= link_to event.name, event %></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= link_to(Location.find_by(id: event.location).name, event.location) %></td>
        <td><%= link_to 'Details', event %></td>
        <td><%= link_to 'Bearbeiten', edit_event_path(event) %></td>
        <td><%= link_to 'Löschen', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neuer Event', new_event_path %>

app/views/events/new.html.erb
<h1>Neuer Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Zurück', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%=@event.name%></h2>
<table class="table">
<tr> <td>Name:</td> <td><%= @event.name %></td></tr>
  <tr> <td>Date:</td> <td><%= I18n.localize @event.date %></td></tr>
  <tr><td>Description:</td><td><%= @event.description %></td></tr>
  <tr> <td>Location:</td> <td><%= Location.find(@event.location).name %></td></tr>
</table>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>