config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :shifts
  end
  resources :locations do
    resource :shift_locations
  end
root 'welcome#index'
end

app/models/shift.rb
class Shift < ApplicationRecord
  has_many :users
  belongs_to :shift_location
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shift, only: [:show, :edit, :update, :destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html {redirect_to @shift, notice: 'Shift was successfully created.'}
        format.json {render :show, status: :created, location: @shift}
      else
        format.html {render :new}
        format.json {render json: @shift.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html {redirect_to @shift, notice: 'Shift was successfully updated.'}
        format.json {render :show, status: :ok, location: @shift}
      else
        format.html {render :edit}
        format.json {render json: @shift.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html {redirect_to shifts_url, notice: 'Shift was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_shift
    @shift = Shift.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shift_params
    params.fetch(:shift, {})
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_with(model: shift, local: true) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shifts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>